name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notification-test:
    runs-on: ubuntu-latest
    name: Notification Test

    strategy:
      matrix:
        platform: [android, ios, macos, web]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Build Notification
        uses: ./
        with:
          platform: ${{ matrix.platform }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          build-name: 1.0.0
          build-number: 20231005
          changelog: |
            ## Changelog
            - Added new feature
            - Fixed bug
