name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notification-test:
    runs-on: ubuntu-latest
    name: Notification Test

    strategy:
      matrix:
        platform: [android, ios, macos, web]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "Foo bar baz"
            }
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        if: always()
